#!/bin/bash -e

for filename in "$@"; do
	lcmds=()

	exec 3<&0
	exec <"$filename"

	exec 4<&1
	exec >"${filename}.new"

	supress=no
	cmd=''
	lcmd=''
	ln=0
	while read -r line; do
		((++ln))
		case "$line" in
		\#\>\>\ *)
			echo "$line"

			c="${line#'#>> '}"
			if [[ $line =~ .*\\$ ]]; then
				c="${c%\\}"
				cmd="$cmd $c"$'\n'
			else
				cmd="$cmd $c"$'\n'
				if ! eval "$cmd"; then
					echo 'Failed to evaluate: '$cmd >&2
					echo 'At line: '$ln >&2
					exit 1
				fi
				cmd=''
				supress=yes
			fi
			;;
		\#\>\!\ *)
			echo "$line"

			c="${line#'#>! '}"
			if [[ $line =~ .*\\$ ]]; then
				c="${c%\\}"
				lcmd="$lcmd $c"$'\n'
			else
				lcmd="$lcmd $c"$'\n'
				lcmds+=("$lcmd")
				lcmd=''
			fi
			;;
		*)
			cmd=''
			lcmd=''
			if [ $supress = yes ]; then
				supress=no
			else
				echo "$line"
			fi
		esac
	done
	exec <&3 3<&-
	exec >&4 4>&-

	mv "${filename}" "${filename}.old"
	mv "${filename}.new" "${filename}"

	for lcmd in "${lcmds[@]}"; do
		echo "$lcmd"
		eval "$lcmd"
	done
done
