#!/bin/bash -e

__uc_prefix='##'

while [ "$#" != 0 ]; do

while getopts 'c:' arg; do
	case "$arg" in
		c)
			__uc_prefix="$OPTARG"
	esac
done

shift $((OPTIND-1))

file=$1

shift

(

__uc_cmd=
__uc_cmds=
__uc_copy=yes
__uc_eob=

exec 3<&0 <"$file" 4>&1 >"$file.new"
while IFS= read -r __uc_line; do
	if [ "$__uc_copy" = no ]; then
		if [ "$__uc_eob" == "$__uc_line" ]; then
			__uc_copy=yes
		else
			continue
		fi
	fi
	if [ -n "$__uc_cmds" ] ; then
		case "$__uc_line" in
			"$__uc_prefix>"*)
				;;
			*)
				eval "$__uc_cmds"
				__uc_cmds=
				;;
		esac
	fi
	case "$__uc_line" in
		"$__uc_prefix>"*)
			__uc_cmd="${__uc_line#$__uc_prefix>}"
			if [ -z "$__uc_cmds" ]; then
				__uc_cmds="$__uc_cmd"
			else
				__uc_cmds="$__uc_cmds"$'\n'"$__uc_cmd"
			fi
			;;
		"$__uc_prefix BEGIN "*)
			__uc_copy=no
			__uc_cmd=${__uc_line#$__uc_prefix BEGIN }
			__uc_eob="$__uc_prefix END $__uc_cmd"
			echo "$__uc_line"
			eval "$__uc_cmd"
			;;
	esac
	if [ "$__uc_copy" = yes ]; then
		echo "$__uc_line"
	fi
done
exec <&3 3<&- >&4 4>&-

cp "$file" "$file.old"
mv "$file.new" "$file"

)

done
